name: "Dependencies Workflow"

# Default permissions for all jobs
permissions: read-all

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at midnight
  workflow_dispatch:

jobs:
  dependency-check:
    permissions:
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      # Add your dependency scanning steps here
      # For example, using safety or dependabot

  update-dependencies:
    permissions:
      contents: write  # Required for pushing changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Update to v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      # Configure Poetry to create the virtual environment in the project root
      - name: Configure Poetry virtualenv location
        run: poetry config virtualenvs.in-project true

      # Cache the virtual environment based on the poetry.lock file
      - name: Cache virtual environment
        uses: actions/cache@v4  # Update to v4
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            venv-${{ runner.os }}-

      - name: Install Dependencies
        run: poetry install

      - name: Update Dependencies
        run: poetry update

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add poetry.lock
          git commit -m "Update Poetry dependencies" || echo "No changes to commit"

      - name: Push Changes
        # Use built-in push instead of third-party action
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
